### ISSUE TITLE
snippets does not show

### ISSUE THREAD

**Issue by DRYN07** [dozius/keypirinha-snippets#6]
I made a bunch of snippets and it worked well. After I reinstalled Windows, I can see the snippet name but after TAB the list are not showing. I use Keypirinha as portable and I tried to refresh all packages. Any help would be appreciated.

UPDATE: My fault sorry, syntax...

**Comment by ccarpo** [comment]
Sorry to continue on this. But I have a similar problem.
It was working for some years. Now its not. 
The console loads the plugin successfully.
The snippets.ini is there with some entries. 
I tried to refresh the catalog. Snippets is not listed there like other Plugins with XXX Cataloged xxx items in xx seconds
If I type "snip" in the Searchbox he shows me the right keyword. But TAB does not show any entries. 
Any ideas what I can do to check whats wrong?

UPDATE: ok after fiddeling with a clean version I noticed that the snip keyword is gone and not used anymore. and that my snippets.ini used the wrong prefix (snippet instead of snippets) so the entries are displayed directly in the catalog (as clearly stated in the readme. Mea Culpae. )
Strangely in my old environment the "snip" keyword is still there, which confused me. If I am able to remove it I'll update my post.
